name: Starlight CI

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**" # This is the path to the workflow files
      - "src/**" # Any source files

env:
  IS_CI: 1 # Let the build know that it's running in CI, so it doesn't run stuff that'll fail

jobs:
  ci:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1.1

    - name: Setup NUnit
      run: nuget install NUnit.ConsoleRunner -Version 3.15.2 -OutputDirectory nunit

    - name: Restore packages
      run: nuget restore Starlight.sln

    - name: Build solution
      run: msbuild.exe Starlight.sln -p:Configuration=Release

    - name: Run tests
      run: testrunner/NUnit.ConsoleRunner.3.15.2/tools/nunit3-console.exe src/Starlight.Test/bin/Release/Starlight.Test.dll

    - name: Upload artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: bundle
        path: "bin/Release/"

    - name: Upload test artifacts # Maybe useful for debugging...
      uses: actions/upload-artifact@v1.0.0
      with:
        name: test-results
        path: |
          "TestResult.xml"
          "src/Starlight.Test/bin/Release/Logs/"